#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/hello.java /autograder/source/hello.java

cd /autograder/source
javac hello.java

python3 run_tests.py > /autograder/results/results.json
